api-version: 1.21
name: FirstPlugin
version: 0.0.1
author: Herethon
main: fr.herethon.firstplugin.FirstPlugin
load: STARTUP
commands:
  test:
    description: This is a test command.
    permission: test.use  
  alert:
    description: This is a custom broadcast.
    permission: bc.use
  spawn:
    description: This is a command to teleport back to spawn.
    permission: spawn.use